In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.4'

In [3]:
np.array([1, 2, 4, 3, 5])

array([1, 2, 4, 3, 5])

In [4]:
np.array([1, 4, "7", 8, False])

array(['1', '4', '7', '8', 'False'], dtype='<U21')

In [5]:
sample_List = [1, 3, 5, 7, 9]

In [6]:
print(sample_List)

[1, 3, 5, 7, 9]


In [8]:
sample_List*4

[1, 3, 5, 7, 9, 1, 3, 5, 7, 9, 1, 3, 5, 7, 9, 1, 3, 5, 7, 9]

In [9]:
sample_numpy_array = np.array([1, 3, 5, 7, 9])

In [10]:
sample_numpy_array

array([1, 3, 5, 7, 9])

In [11]:
sample_numpy_array*4

array([ 4, 12, 20, 28, 36])

In [12]:
#Creating_a_matrix

a = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

In [13]:
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
a = np.array(a)

In [15]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
a[0][1]

np.int64(2)

In [20]:
# Creating a 3x3 array of random integers in the interval[0, 10]

np.random.randint(0, 10, (3, 3))

array([[7, 3, 6],
       [5, 5, 9],
       [7, 2, 7]], dtype=int32)

In [23]:
# Fixing the random seed

np.random.seed(0)
np.random.randint(0, 10, (3, 3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]], dtype=int32)

In [24]:
np.zeros((4, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [25]:
np.zeros((3, 3), dtype=float)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones((2, 10), dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [27]:
np.identity(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [28]:
np.full((3, 5), 2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])